//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleStreamsLab.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleStreamsLab.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enumerateprocessmodules.
        /// </summary>
        internal static string ENUMERATE_PROCESS_MODULES {
            get {
                return ResourceManager.GetString("ENUMERATE_PROCESS_MODULES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please press Return to fully stop the program..
        /// </summary>
        internal static string MSG_AWAIT_CARBON_UNIT {
            get {
                return ResourceManager.GetString("MSG_AWAIT_CARBON_UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, version {1}.{2},{5}{3} ({4} UTC){5}.
        /// </summary>
        internal static string MSG_START {
            get {
                return ResourceManager.GetString("MSG_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process started in a console window, and is attaching itself to a debugger.{0}.
        /// </summary>
        internal static string MSG_STARTED_IN_CONSOLE {
            get {
                return ResourceManager.GetString("MSG_STARTED_IN_CONSOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process started with a debugger attached to it.{0}.
        /// </summary>
        internal static string MSG_STARTED_IN_DEBUGGER {
            get {
                return ResourceManager.GetString("MSG_STARTED_IN_DEBUGGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Properties of Standard Handle {0}:{1}.
        /// </summary>
        internal static string MSG_STD_HANDLE_BEGIN {
            get {
                return ResourceManager.GetString("MSG_STD_HANDLE_BEGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}    End of {0} properties{1}.
        /// </summary>
        internal static string MSG_STD_HANDLE_END {
            get {
                return ResourceManager.GetString("MSG_STD_HANDLE_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STDERR (Standard Error).
        /// </summary>
        internal static string MSG_STDERR {
            get {
                return ResourceManager.GetString("MSG_STDERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STDIN (Stnadard Input).
        /// </summary>
        internal static string MSG_STDIN {
            get {
                return ResourceManager.GetString("MSG_STDIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STDOUT (Standard Output).
        /// </summary>
        internal static string MSG_STDOUT {
            get {
                return ResourceManager.GetString("MSG_STDOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {4}{0} Done, {1} ({2} UTC){4}Running time = {3}.
        /// </summary>
        internal static string MSG_STOP {
            get {
                return ResourceManager.GetString("MSG_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNSUPPORTED.
        /// </summary>
        internal static string MSG_UNSUPPORTED_FEATURE {
            get {
                return ResourceManager.GetString("MSG_UNSUPPORTED_FEATURE", resourceCulture);
            }
        }
    }
}
