//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WizardWrx.DLLServices2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WizardWrx.DLLServices2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to penmConstructionStage.
        /// </summary>
        public static string ARGNAME_PENMCONSTRUCTIONSTAGE {
            get {
                return ResourceManager.GetString("ARGNAME_PENMCONSTRUCTIONSTAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultWindowsEventSourceID.
        /// </summary>
        public static string DEFAULT_EVENT_SOURCE_ID {
            get {
                return ResourceManager.GetString("DEFAULT_EVENT_SOURCE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of aliases is empty..
        /// </summary>
        public static string EMPTY_ALIAS_LIST {
            get {
                return ResourceManager.GetString("EMPTY_ALIAS_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified argument is a null reference..
        /// </summary>
        public static string ERRMSG_ARG_IS_NULL {
            get {
                return ResourceManager.GetString("ERRMSG_ARG_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument is a null reference or the empty string..
        /// </summary>
        public static string ERRMSG_ARG_IS_NULL_OR_EMPTY {
            get {
                return ResourceManager.GetString("ERRMSG_ARG_IS_NULL_OR_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument Name    = {0}{1}.
        /// </summary>
        public static string ERRMSG_ARGNAME_TPL {
            get {
                return ResourceManager.GetString("ERRMSG_ARGNAME_TPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument Value   = {0}{1}.
        /// </summary>
        public static string ERRMSG_ARGVALUE_TPL {
            get {
                return ResourceManager.GetString("ERRMSG_ARGVALUE_TPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While attempting to identify the subsystem of {0}, GetExeSubsystem returned exit code {1}: {2}.
        /// </summary>
        public static string ERRMSG_ASM_SUBSYSTEM {
            get {
                return ResourceManager.GetString("ERRMSG_ASM_SUBSYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified DLL configuration file, {0}, exists, but is empty.
        /// </summary>
        public static string ERRMSG_CONFIG_FILE_IS_EMPTY {
            get {
                return ResourceManager.GetString("ERRMSG_CONFIG_FILE_IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch {0} with a default value of {1} is a duplicate..
        /// </summary>
        public static string ERRMSG_DUPLICATE_SWITCH {
            get {
                return ResourceManager.GetString("ERRMSG_DUPLICATE_SWITCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource {0} cannot be found in assembly {1}..
        /// </summary>
        public static string ERRMSG_EMBEDDED_RESOURCE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERRMSG_EMBEDDED_RESOURCE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while reading data from resources embedded in an assembly.{3}Assembly Full Name     = {0}{3}Internal Resource Name = {1}{3}I/O Error Message      = {2}{3}{3}The associated Inner Exception may contain additional clues..
        /// </summary>
        public static string ERRMSG_EMBEDDED_RESOURCE_READ_ERROR {
            get {
                return ResourceManager.GetString("ERRMSG_EMBEDDED_RESOURCE_READ_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while reading a file from resources embedded in an assembly.{3}Internal Name = {0}{3}Expected File Length (bytes) = {1}{3}Bytes successfully read = {2}.
        /// </summary>
        public static string ERRMSG_EMBEDDED_RESOURCE_READ_TRUNCATED {
            get {
                return ResourceManager.GetString("ERRMSG_EMBEDDED_RESOURCE_READ_TRUNCATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An {0} exception was caught in routine {1}:{3}               Message          = {2}{3}.
        /// </summary>
        public static string ERRMSG_EX_EVTMSG_TPL {
            get {
                return ResourceManager.GetString("ERRMSG_EX_EVTMSG_TPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An {0} exception was caught in routine {1}:{3}               Message          = {2}{3}.
        /// </summary>
        public static string ERRMSG_EX_MSG_TPL {
            get {
                return ResourceManager.GetString("ERRMSG_EX_MSG_TPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An {0} Exception was caught while attempting to define a switch named {1} with a default value of {2}.
        /// </summary>
        public static string ERRMSG_EXCEPTION_IN_DEFINE_NEW_SWITCH {
            get {
                return ResourceManager.GetString("ERRMSG_EXCEPTION_IN_DEFINE_NEW_SWITCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name        = {0}{1}.
        /// </summary>
        public static string ERRMSG_FILENAME_TPL {
            get {
                return ResourceManager.GetString("ERRMSG_FILENAME_TPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format String    = {0}{1}.
        /// </summary>
        public static string ERRMSG_FORMATSTRING_TPL {
            get {
                return ResourceManager.GetString("ERRMSG_FORMATSTRING_TPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HRESULT = {0} ({1} decimal){2}.
        /// </summary>
        public static string ERRMSG_HRESULT {
            get {
                return ResourceManager.GetString("ERRMSG_HRESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner Exception:{1}               Message          = {0}{1}.
        /// </summary>
        public static string ERRMSG_INNER {
            get {
                return ResourceManager.GetString("ERRMSG_INNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the first argument, pintegralValue, is invalid.{2}Argument value = {0}{2}Argument type  = {1}{2}{2}Limitations of the underlying formatting engine{2}restrict this method to integral types.{2}.
        /// </summary>
        public static string ERRMSG_INTEGER2HEXSTR_INVALID_INPUT {
            get {
                return ResourceManager.GetString("ERRMSG_INTEGER2HEXSTR_INVALID_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error has occurred.{1}Internal routine GetReservedErrorMessage was called with an invalid ErrorExitOptions value of {0}..
        /// </summary>
        public static string ERRMSG_INVALID_ERROREXITOPTIONS {
            get {
                return ResourceManager.GetString("ERRMSG_INVALID_ERROREXITOPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Method = {0}{1}.
        /// </summary>
        public static string ERRMSG_METHOD {
            get {
                return ResourceManager.GetString("ERRMSG_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no valid configuration file for DLL file {0}..
        /// </summary>
        public static string ERRMSG_MISSING_CONFIG_FILE {
            get {
                return ResourceManager.GetString("ERRMSG_MISSING_CONFIG_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EnhancedIOException is unexpectedly null, probably due to an internal error..
        /// </summary>
        public static string ERRMSG_NULL_EnhancedIOException {
            get {
                return ResourceManager.GetString("ERRMSG_NULL_EnhancedIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Name      = {0}{1}.
        /// </summary>
        public static string ERRMSG_OBJNAME_TPL {
            get {
                return ResourceManager.GetString("ERRMSG_OBJNAME_TPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A run-time exception forced the program to end prematurely.{0}Pleasr see he (0) event log for a message with event source = (0)..
        /// </summary>
        public static string ERRMSG_RUNTIME_SEE_EVENT_LOG {
            get {
                return ResourceManager.GetString("ERRMSG_RUNTIME_SEE_EVENT_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A run-time exception forced the program to end prematurely.{0}Please see the message just above this line..
        /// </summary>
        public static string ERRMSG_RUNTIME_SEE_MESSAGE_ABOVE {
            get {
                return ResourceManager.GetString("ERRMSG_RUNTIME_SEE_MESSAGE_ABOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Source = {0}{1}.
        /// </summary>
        public static string ERRMSG_SOURCE {
            get {
                return ResourceManager.GetString("ERRMSG_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The StandardHandleState routine reported an exception.\nException Code = 0x{0} ({1} decimal): {2}.
        /// </summary>
        public static string ERRMSG_STD_HANDLE_STATE {
            get {
                return ResourceManager.GetString("ERRMSG_STD_HANDLE_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sizes of internal tables s_astrTrimStart and s_astrExceptionTypeNames are unequal.{2}    s_astrTrimStart Elemnent Count          = {0}{2}    s_astrExceptionTypeNames  Elemnent Count = {1}{2}.
        /// </summary>
        public static string ERRMSG_UNBALANCED {
            get {
                return ResourceManager.GetString("ERRMSG_UNBALANCED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FatalExceptionBackgroundColor.
        /// </summary>
        public static string FATAL_EXCEPTION_BACKCOLOR {
            get {
                return ResourceManager.GetString("FATAL_EXCEPTION_BACKCOLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FatalExceptionTextColor.
        /// </summary>
        public static string FATAL_EXCEPTION_FORECOLOR {
            get {
                return ResourceManager.GetString("FATAL_EXCEPTION_FORECOLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is an EFI Application..
        /// </summary>
        public static string IMAGE_SUBSYSTEM_EFI_APPLICATION {
            get {
                return ResourceManager.GetString("IMAGE_SUBSYSTEM_EFI_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is a EFI Boot Service Driver..
        /// </summary>
        public static string IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER {
            get {
                return ResourceManager.GetString("IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image runs from a EFI ROM..
        /// </summary>
        public static string IMAGE_SUBSYSTEM_EFI_ROM {
            get {
                return ResourceManager.GetString("IMAGE_SUBSYSTEM_EFI_ROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is a EFI Runtime Driver..
        /// </summary>
        public static string IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER {
            get {
                return ResourceManager.GetString("IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image doesn&apos;t require a subsystem..
        /// </summary>
        public static string IMAGE_SUBSYSTEM_NATIVE {
            get {
                return ResourceManager.GetString("IMAGE_SUBSYSTEM_NATIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is a native Win9x driver..
        /// </summary>
        public static string IMAGE_SUBSYSTEM_NATIVE_WINDOWS {
            get {
                return ResourceManager.GetString("IMAGE_SUBSYSTEM_NATIVE_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image runs in the OS/2 character subsystem..
        /// </summary>
        public static string IMAGE_SUBSYSTEM_OS2_CUI {
            get {
                return ResourceManager.GetString("IMAGE_SUBSYSTEM_OS2_CUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image runs in the Posix character subsystem..
        /// </summary>
        public static string IMAGE_SUBSYSTEM_POSIX_CUI {
            get {
                return ResourceManager.GetString("IMAGE_SUBSYSTEM_POSIX_CUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified image subsystem ID, {0} is undefined..
        /// </summary>
        public static string IMAGE_SUBSYSTEM_UNDEFINED_VALUE {
            get {
                return ResourceManager.GetString("IMAGE_SUBSYSTEM_UNDEFINED_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown subsystem..
        /// </summary>
        public static string IMAGE_SUBSYSTEM_UNKNOWN {
            get {
                return ResourceManager.GetString("IMAGE_SUBSYSTEM_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image runs in the Windows CE subsystem..
        /// </summary>
        public static string IMAGE_SUBSYSTEM_WINDOWS_CE_GUI {
            get {
                return ResourceManager.GetString("IMAGE_SUBSYSTEM_WINDOWS_CE_GUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image runs in the Windows character subsystem..
        /// </summary>
        public static string IMAGE_SUBSYSTEM_WINDOWS_CUI {
            get {
                return ResourceManager.GetString("IMAGE_SUBSYSTEM_WINDOWS_CUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image runs in the Windows GUI subsystem..
        /// </summary>
        public static string IMAGE_SUBSYSTEM_WINDOWS_GUI {
            get {
                return ResourceManager.GetString("IMAGE_SUBSYSTEM_WINDOWS_GUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image runs on XBOX..
        /// </summary>
        public static string IMAGE_SUBSYSTEM_XBOX {
            get {
                return ResourceManager.GetString("IMAGE_SUBSYSTEM_XBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GetStdHandleFQFN routine supports only character mode (console mode) applications..
        /// </summary>
        public static string MSG_APP_CHARACTER_MODE_APPS_ONLY {
            get {
                return ResourceManager.GetString("MSG_APP_CHARACTER_MODE_APPS_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     AssemblyFileBaseName = {0}.
        /// </summary>
        public static string MSG_ASM_PROPS_ASSEMBLYFILEBASENAME {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_ASSEMBLYFILEBASENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     AssemblyFileName     = {0}{1}.
        /// </summary>
        public static string MSG_ASM_PROPS_ASSEMBLYFILENAME {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_ASSEMBLYFILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     AssemblyGuidString   = {0}.
        /// </summary>
        public static string MSG_ASM_PROPS_ASSEMBLYGUIDSTRING {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_ASSEMBLYGUIDSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     AssembyDirName       = {0}.
        /// </summary>
        public static string MSG_ASM_PROPS_ASSEMBYDIRNAME {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_ASSEMBYDIRNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Comments             = {0}{1}.
        /// </summary>
        public static string MSG_ASM_PROPS_COMMENTS {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_COMMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     CompanyName          = {0}.
        /// </summary>
        public static string MSG_ASM_PROPS_COMPANYNAME {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_COMPANYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Culture              = {0}.
        /// </summary>
        public static string MSG_ASM_PROPS_CULTURE {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_CULTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Description          = {0}.
        /// </summary>
        public static string MSG_ASM_PROPS_DESCRIPTION {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     File Creation Date   = {0} ({1} UTC).
        /// </summary>
        public static string MSG_ASM_PROPS_FILE_CREATION_DATE {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_FILE_CREATION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     File Modified Date   = {0} ({1} UTC).
        /// </summary>
        public static string MSG_ASM_PROPS_FILE_MODIFIED_DATE {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_FILE_MODIFIED_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     LegalCopyright       = {0}.
        /// </summary>
        public static string MSG_ASM_PROPS_LEGALCOPYRIGHT {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_LEGALCOPYRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     LegalTrademarks      = {0}.
        /// </summary>
        public static string MSG_ASM_PROPS_LEGALTRADEMARKS {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_LEGALTRADEMARKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     ProductName          = {0}.
        /// </summary>
        public static string MSG_ASM_PROPS_PRODUCTNAME {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_PRODUCTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     PublicKeyToken       = {0}.
        /// </summary>
        public static string MSG_ASM_PROPS_PUBLICKEYTOKEN {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_PUBLICKEYTOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Runtime Version      = {0}.
        /// </summary>
        public static string MSG_ASM_PROPS_RUNTIME_VERSION {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_RUNTIME_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected properties of the library under test:{0}.
        /// </summary>
        public static string MSG_ASM_PROPS_SELECTED_DLL_PROPS_BEGIN {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_SELECTED_DLL_PROPS_BEGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}End of selected properties{0}.
        /// </summary>
        public static string MSG_ASM_PROPS_SELECTED_DLL_PROPS_END {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_SELECTED_DLL_PROPS_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     VersionString        = {0}.
        /// </summary>
        public static string MSG_ASM_PROPS_VERSIONSTRING {
            get {
                return ResourceManager.GetString("MSG_ASM_PROPS_VERSIONSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , NOT redirected.
        /// </summary>
        public static string MSG_CONSOLE_HAS_STD_HANDLE {
            get {
                return ResourceManager.GetString("MSG_CONSOLE_HAS_STD_HANDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutputOptions {0}= {1} ({2} decimal = {3}).
        /// </summary>
        public static string OUTPUT_OPTIONS_DISPLAY_FORMAT {
            get {
                return ResourceManager.GetString("OUTPUT_OPTIONS_DISPLAY_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, version {1}.
        /// </summary>
        public static string PRODUCT_NAME_AND_VERSION_TPL {
            get {
                return ResourceManager.GetString("PRODUCT_NAME_AND_VERSION_TPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorMessageColors.
        /// </summary>
        public static string PROPID_ERROR_MSG_COLOR {
            get {
                return ResourceManager.GetString("PROPID_ERROR_MSG_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecoverableExceptionBackgroundColor.
        /// </summary>
        public static string RECOVERABLE_EXCEPTION_BACKCOLOR {
            get {
                return ResourceManager.GetString("RECOVERABLE_EXCEPTION_BACKCOLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecoverablelExceptionTextColor.
        /// </summary>
        public static string RECOVERABLE_EXCEPTION_FORECOLOR {
            get {
                return ResourceManager.GetString("RECOVERABLE_EXCEPTION_FORECOLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}Stack Trace Begin:{1}{0}{1}End of Stack Trace{1}{1}.
        /// </summary>
        public static string STACKTRACE_TPL {
            get {
                return ResourceManager.GetString("STACKTRACE_TPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        public static string SWITCH_IS_OFF {
            get {
                return ResourceManager.GetString("SWITCH_IS_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        public static string SWITCH_IS_ON {
            get {
                return ResourceManager.GetString("SWITCH_IS_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of {1} specified for argument {0} is invalid..
        /// </summary>
        public static string TDF_INVALID_ARG_VALUE {
            get {
                return ResourceManager.GetString("TDF_INVALID_ARG_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new value of {1} specified for the {0} property is invalid.{3}The previous value of {2} is retained..
        /// </summary>
        public static string TDF_INVALID_ENUM_VALUE {
            get {
                return ResourceManager.GetString("TDF_INVALID_ENUM_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no further exceptions to report.{0}.
        /// </summary>
        public static string THIS_IS_THE_LAST {
            get {
                return ResourceManager.GetString("THIS_IS_THE_LAST", resourceCulture);
            }
        }
    }
}
