//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedirectedStreamTester.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RedirectedStreamTester.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stderr.
        /// </summary>
        internal static string ARGNAME_STDERR {
            get {
                return ResourceManager.GetString("ARGNAME_STDERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stdin.
        /// </summary>
        internal static string ARGNAME_STDIN {
            get {
                return ResourceManager.GetString("ARGNAME_STDIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stdout.
        /// </summary>
        internal static string ARGNAME_STDOUT {
            get {
                return ResourceManager.GetString("ARGNAME_STDOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string ARGVALUE_DEFAULT {
            get {
                return ResourceManager.GetString("ARGVALUE_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirected.
        /// </summary>
        internal static string ARGVALUE_REDIRECTED {
            get {
                return ResourceManager.GetString("ARGVALUE_REDIRECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, version {1} BOJ{4}{2} ({3} UTC).
        /// </summary>
        internal static string BOJ_MSG_TPL {
            get {
                return ResourceManager.GetString("BOJ_MSG_TPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} EOJ{2}Running time = {1}{2}Press ENTER to exit the program..
        /// </summary>
        internal static string EOJ_MSG_TPL {
            get {
                return ResourceManager.GetString("EOJ_MSG_TPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A run-time exception was caught and reported..
        /// </summary>
        internal static string ERRMSG_RUNTIME {
            get {
                return ResourceManager.GetString("ERRMSG_RUNTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} exception was caught in routine {1}, while processing its {2} argument. Details follow.{4}{3}.
        /// </summary>
        internal static string ERRMSG_STREAMSTATE_CTOR {
            get {
                return ResourceManager.GetString("ERRMSG_STREAMSTATE_CTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state value of argument {0} is invalid.{2}Its value, {1}, contains too many commas..
        /// </summary>
        internal static string ERRMSG_STREAMSTATE_FORMAT {
            get {
                return ResourceManager.GetString("ERRMSG_STREAMSTATE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing completed without errors..
        /// </summary>
        internal static string ERRMSG_SUCCESS {
            get {
                return ResourceManager.GetString("ERRMSG_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     STDERR State, per Command Line = {0}{1}.
        /// </summary>
        internal static string LOGMSG_ACTUAL_STDERR_STATE {
            get {
                return ResourceManager.GetString("LOGMSG_ACTUAL_STDERR_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     STDIN State, per Command Line  = {0}{1}.
        /// </summary>
        internal static string LOGMSG_ACTUAL_STDIN_STATE {
            get {
                return ResourceManager.GetString("LOGMSG_ACTUAL_STDIN_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     STDOUT State, per Command Line = {0}{1}.
        /// </summary>
        internal static string LOGMSG_ACTUAL_STDOUT_STATE {
            get {
                return ResourceManager.GetString("LOGMSG_ACTUAL_STDOUT_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}    Assembly ImageRuntimeVersion   = {1}{2}.
        /// </summary>
        internal static string LOGMSG_ASSEMBLY_RUNTIME_VER {
            get {
                return ResourceManager.GetString("LOGMSG_ASSEMBLY_RUNTIME_VER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Working Directory              = {0}{0}{1}.
        /// </summary>
        internal static string LOGMSG_CWD {
            get {
                return ResourceManager.GetString("LOGMSG_CWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} EOJ{2}Running time = {1}.
        /// </summary>
        internal static string LOGMSG_EOJ {
            get {
                return ResourceManager.GetString("LOGMSG_EOJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     STDERR State, per .NET BCL     = {0}{1}.
        /// </summary>
        internal static string LOGMSG_REPORTED_STDERR_STATE {
            get {
                return ResourceManager.GetString("LOGMSG_REPORTED_STDERR_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     STDIN State, per .NET BCL      = {0}{1}.
        /// </summary>
        internal static string LOGMSG_REPORTED_STDIN_STATE {
            get {
                return ResourceManager.GetString("LOGMSG_REPORTED_STDIN_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     STDOUT State, per .NET BCL     = {0}{1}.
        /// </summary>
        internal static string LOGMSG_REPORTED_STDOUT_STATE {
            get {
                return ResourceManager.GetString("LOGMSG_REPORTED_STDOUT_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is resuming..
        /// </summary>
        internal static string LOGMSG_RESUMING {
            get {
                return ResourceManager.GetString("LOGMSG_RESUMING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Parameters:{0}.
        /// </summary>
        internal static string LOGMSG_RUN_PARAMETERS {
            get {
                return ResourceManager.GetString("LOGMSG_RUN_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}State of the file system at {0}{1}.
        /// </summary>
        internal static string LOGMSG_STATE_OF_AFFAIRS {
            get {
                return ResourceManager.GetString("LOGMSG_STATE_OF_AFFAIRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directed to the default stream (the console)..
        /// </summary>
        internal static string LOGMSG_STREAM_DEFAULT {
            get {
                return ResourceManager.GetString("LOGMSG_STREAM_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                  Last Access Time  = {0}{1}.
        /// </summary>
        internal static string LOGMSG_STREAM_FILE_ACCESSED {
            get {
                return ResourceManager.GetString("LOGMSG_STREAM_FILE_ACCESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                  Created Time      = {0}{1}.
        /// </summary>
        internal static string LOGMSG_STREAM_FILE_CREATED {
            get {
                return ResourceManager.GetString("LOGMSG_STREAM_FILE_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                  Last Write Time   = {0}{1}.
        /// </summary>
        internal static string LOGMSG_STREAM_FILE_MODIFIED {
            get {
                return ResourceManager.GetString("LOGMSG_STREAM_FILE_MODIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                  File Exists       = {0}{1}.
        /// </summary>
        internal static string LOGMSG_STREAM_FILE_PRESENT {
            get {
                return ResourceManager.GetString("LOGMSG_STREAM_FILE_PRESENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                  Reported Size     = {0}{1}.
        /// </summary>
        internal static string LOGMSG_STREAM_FILE_SIZE {
            get {
                return ResourceManager.GetString("LOGMSG_STREAM_FILE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     {0,-6} File: Quualified Name   = {1}{2}.
        /// </summary>
        internal static string LOGMSG_STREAM_FILE_STATE {
            get {
                return ResourceManager.GetString("LOGMSG_STREAM_FILE_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirected to a file.
        /// </summary>
        internal static string LOGMSG_STREAM_REDIRECTED {
            get {
                return ResourceManager.GetString("LOGMSG_STREAM_REDIRECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNKNOWN.
        /// </summary>
        internal static string LOGMSG_STREAM_STATE_UNKNOWN {
            get {
                return ResourceManager.GetString("LOGMSG_STREAM_STATE_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at startup.
        /// </summary>
        internal static string LOGMSG_TASK_STAGE_BOJ {
            get {
                return ResourceManager.GetString("LOGMSG_TASK_STAGE_BOJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at shutdown.
        /// </summary>
        internal static string LOGMSG_TASK_STAGE_EOJ {
            get {
                return ResourceManager.GetString("LOGMSG_TASK_STAGE_EOJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has completed its initial reports..
        /// </summary>
        internal static string LOGMSG_WAIT_FOR_OPERATOR {
            get {
                return ResourceManager.GetString("LOGMSG_WAIT_FOR_OPERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has completed its initial reports.{1}Do whatever you need to verify how things stand.{1}Press RETURN to record the final state of affairs..
        /// </summary>
        internal static string MSG_PROMPT_TO_RESUME {
            get {
                return ResourceManager.GetString("MSG_PROMPT_TO_RESUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirected to {0}.
        /// </summary>
        internal static string MSG_STREAM_REDIRECTED {
            get {
                return ResourceManager.GetString("MSG_STREAM_REDIRECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream Name and Description                          State.
        /// </summary>
        internal static string MSG_STREAM_STATE_LABELS {
            get {
                return ResourceManager.GetString("MSG_STREAM_STATE_LABELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---------------------------------------------------- --------------------------.
        /// </summary>
        internal static string MSG_STREAM_STATE_RULE1 {
            get {
                return ResourceManager.GetString("MSG_STREAM_STATE_RULE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -------------------------------------------------------------------------------.
        /// </summary>
        internal static string MSG_STREAM_STATE_RULE2 {
            get {
                return ResourceManager.GetString("MSG_STREAM_STATE_RULE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-52} {1}.
        /// </summary>
        internal static string MSG_STREAM_STATE_VALUES {
            get {
                return ResourceManager.GetString("MSG_STREAM_STATE_VALUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STDERR (Standard Error), represented by Console.Error.
        /// </summary>
        internal static string MSG_STREAM_STDERR {
            get {
                return ResourceManager.GetString("MSG_STREAM_STDERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STDIN (Standard Input), represented by Console.In.
        /// </summary>
        internal static string MSG_STREAM_STDIN {
            get {
                return ResourceManager.GetString("MSG_STREAM_STDIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STDOUT (Standard Output), represented by Console.Out.
        /// </summary>
        internal static string MSG_STREAM_STDOUT {
            get {
                return ResourceManager.GetString("MSG_STREAM_STDOUT", resourceCulture);
            }
        }
    }
}
