//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeysEnumLab.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeysEnumLab.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} BOJ{2}{1}{2}.
        /// </summary>
        internal static string BOJ_MSG {
            get {
                return ResourceManager.GetString("BOJ_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} EOJ{2}Running Time = {1}{2}.
        /// </summary>
        internal static string EOJ_MSG {
            get {
                return ResourceManager.GetString("EOJ_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2}{0:N0} bytes written to file {1}{2}.
        /// </summary>
        internal static string KEYS_FILE_MSG {
            get {
                return ResourceManager.GetString("KEYS_FILE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{3}{1}{3}{2}.
        /// </summary>
        internal static string KEYS_LBL {
            get {
                return ResourceManager.GetString("KEYS_LBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{2}0x{1:X8}{2}{1}.
        /// </summary>
        internal static string KEYS_LST {
            get {
                return ResourceManager.GetString("KEYS_LST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key = {0,-18}, Value = 0x{1:X8} ({1,10:N0} decimal).
        /// </summary>
        internal static string KEYS_MSG {
            get {
                return ResourceManager.GetString("KEYS_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string KEYS_NAME {
            get {
                return ResourceManager.GetString("KEYS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal.
        /// </summary>
        internal static string KEYS_VALUE_DEC {
            get {
                return ResourceManager.GetString("KEYS_VALUE_DEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex.
        /// </summary>
        internal static string KEYS_VALUE_HEX {
            get {
                return ResourceManager.GetString("KEYS_VALUE_HEX", resourceCulture);
            }
        }
    }
}
