//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BinaryPropertyStorage.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BinaryPropertyStorage.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TabStopJustLeft new property value must be a valid TabIndex (greater than zero)..
        /// </summary>
        internal static string ERRMSG_TABSTOPLEFT_VALUE_DETAIL {
            get {
                return ResourceManager.GetString("ERRMSG_TABSTOPLEFT_VALUE_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TabStopJustLeft new property value.
        /// </summary>
        internal static string ERRMSG_TABSTOPLEFT_VALUE_NAME {
            get {
                return ResourceManager.GetString("ERRMSG_TABSTOPLEFT_VALUE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASCII.
        /// </summary>
        internal static string FRMLBL_ENC_CBO_ASCII {
            get {
                return ResourceManager.GetString("FRMLBL_ENC_CBO_ASCII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode.
        /// </summary>
        internal static string FRMLBL_ENC_CBO_UNICODE {
            get {
                return ResourceManager.GetString("FRMLBL_ENC_CBO_UNICODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTF-32.
        /// </summary>
        internal static string FRMLBL_ENC_CBO_UTF_32 {
            get {
                return ResourceManager.GetString("FRMLBL_ENC_CBO_UTF_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTF-7.
        /// </summary>
        internal static string FRMLBL_ENC_CBO_UTF_7 {
            get {
                return ResourceManager.GetString("FRMLBL_ENC_CBO_UTF_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTF-8.
        /// </summary>
        internal static string FRMLBL_ENC_CBO_UTF_8 {
            get {
                return ResourceManager.GetString("FRMLBL_ENC_CBO_UTF_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string FRMLBL_PRD_CMDBROWSEFORDIRECTORY {
            get {
                return ResourceManager.GetString("FRMLBL_PRD_CMDBROWSEFORDIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Directory.
        /// </summary>
        internal static string FRMLBL_PRD_LBLWORKINGDIRECTORY {
            get {
                return ResourceManager.GetString("FRMLBL_PRD_LBLWORKINGDIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Profile.
        /// </summary>
        internal static string FRMLBL_PRF_CMDNEWPROFILE {
            get {
                return ResourceManager.GetString("FRMLBL_PRF_CMDNEWPROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string FRMLBL_PRF_CMDPROFILEFILEBROWSER {
            get {
                return ResourceManager.GetString("FRMLBL_PRF_CMDPROFILEFILEBROWSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Profile.
        /// </summary>
        internal static string FRMLBL_PRF_CMDSAVEPROFILE {
            get {
                return ResourceManager.GetString("FRMLBL_PRF_CMDSAVEPROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GUID generated by the SaveProfile routine has an unexpected length of {0} bytes. The expected length is 16 bytes..
        /// </summary>
        internal static string FRMLBL_PRF_ERRMSG_INVALID_GUID_FORMAT {
            get {
                return ResourceManager.GetString("FRMLBL_PRF_ERRMSG_INVALID_GUID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied INT32 entity converted to an unexpected number of bytes; expected 4, got {0}..
        /// </summary>
        internal static string FRMLBL_PRF_ERRMSG_INVALID_INT32_FORMAT {
            get {
                return ResourceManager.GetString("FRMLBL_PRF_ERRMSG_INVALID_INT32_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first column in any row must be a well formed GUID string. The value that is in error is {1}{0}{1}..
        /// </summary>
        internal static string FRMLBL_PRF_ERRMSG_MUST_BE_GUID_STRING {
            get {
                return ResourceManager.GetString("FRMLBL_PRF_ERRMSG_MUST_BE_GUID_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one property must be specified. There are none in row {0} with a GUID of {1}..
        /// </summary>
        internal static string FRMLBL_PRF_ERRMSG_NO_PROPERTIES {
            get {
                return ResourceManager.GetString("FRMLBL_PRF_ERRMSG_NO_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hidden.
        /// </summary>
        internal static string FRMLBL_PRF_HIDECOLUMTOKEN_1_OF_2 {
            get {
                return ResourceManager.GetString("FRMLBL_PRF_HIDECOLUMTOKEN_1_OF_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hide.
        /// </summary>
        internal static string FRMLBL_PRF_HIDECOLUMTOKEN_2_OF_2 {
            get {
                return ResourceManager.GetString("FRMLBL_PRF_HIDECOLUMTOKEN_2_OF_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile File Name.
        /// </summary>
        internal static string FRMLBL_PRF_LBLFILENAME {
            get {
                return ResourceManager.GetString("FRMLBL_PRF_LBLFILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Name.
        /// </summary>
        internal static string FRMLBL_PRF_LBLPROFILENAME {
            get {
                return ResourceManager.GetString("FRMLBL_PRF_LBLPROFILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile metadata save failed..
        /// </summary>
        internal static string FRMLBL_PRF_METADATA_SAVE_FAILED {
            get {
                return ResourceManager.GetString("FRMLBL_PRF_METADATA_SAVE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified working directory was created..
        /// </summary>
        internal static string FRMLBL_PRF_MSG_DIRECTORY_CREATED {
            get {
                return ResourceManager.GetString("FRMLBL_PRF_MSG_DIRECTORY_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified working directory exists..
        /// </summary>
        internal static string FRMLBL_PRF_MSG_DIRECTORY_FOUND {
            get {
                return ResourceManager.GetString("FRMLBL_PRF_MSG_DIRECTORY_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $$WorkingDirectoryName$$ was specified, but hasn&apos;t been created. Create it or select a different directory..
        /// </summary>
        internal static string FRMLBL_PRF_MSG_DIRECTORY_NOT_CREATED {
            get {
                return ResourceManager.GetString("FRMLBL_PRF_MSG_DIRECTORY_NOT_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exist.{1}{1}Do you want to create it?.
        /// </summary>
        internal static string FRMLBL_PRF_MSG_DIRECTORY_NOT_FOUND {
            get {
                return ResourceManager.GetString("FRMLBL_PRF_MSG_DIRECTORY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified profile exists, and it has a file in the specified working directory, which will be overwritten if the profile is saved..
        /// </summary>
        internal static string FRMLBL_PRF_MSG_PROFILE_EXISTS {
            get {
                return ResourceManager.GetString("FRMLBL_PRF_MSG_PROFILE_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified profile is new, and no file exists in the specified working directory..
        /// </summary>
        internal static string FRMLBL_PRF_MSG_PROFILE_IS_BRAND_NEW {
            get {
                return ResourceManager.GetString("FRMLBL_PRF_MSG_PROFILE_IS_BRAND_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile save failed because {0}..
        /// </summary>
        internal static string FRMLBL_PRF_MSG_PROFILE_SAVE_FAILED {
            get {
                return ResourceManager.GetString("FRMLBL_PRF_MSG_PROFILE_SAVE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to profile?.
        /// </summary>
        internal static string FRMLBL_PRF_MSG_PROFILE_SAVE_PROMPT {
            get {
                return ResourceManager.GetString("FRMLBL_PRF_MSG_PROFILE_SAVE_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile saved. {0} bytes written to disk..
        /// </summary>
        internal static string FRMLBL_PRF_MSG_PROFILE_SAVED {
            get {
                return ResourceManager.GetString("FRMLBL_PRF_MSG_PROFILE_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BinaryPropertyMetaData.
        /// </summary>
        internal static string FRMLBL_PRF_PROFILEFILENAMESUFFIX {
            get {
                return ResourceManager.GetString("FRMLBL_PRF_PROFILEFILENAMESUFFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $$WorkingDirectoryName$$\$$ProfileName$$.BIN.
        /// </summary>
        internal static string FRMLBL_PRF_TXTPROFILEFILENAME {
            get {
                return ResourceManager.GetString("FRMLBL_PRF_TXTPROFILEFILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to untitled.
        /// </summary>
        internal static string FRMLBL_PRF_TXTPROFILENAME {
            get {
                return ResourceManager.GetString("FRMLBL_PRF_TXTPROFILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The working directory is unspecified..
        /// </summary>
        internal static string FRMLBL_PRF_TXTPROFILEUNSPECIFIEDCWD {
            get {
                return ResourceManager.GetString("FRMLBL_PRF_TXTPROFILEUNSPECIFIEDCWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply New Labels.
        /// </summary>
        internal static string FRMLBL_PSD_CMDAPPLYNEWLABELS {
            get {
                return ResourceManager.GetString("FRMLBL_PSD_CMDAPPLYNEWLABELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID.
        /// </summary>
        internal static string FRMLBL_PSD_ITEMGUID {
            get {
                return ResourceManager.GetString("FRMLBL_PSD_ITEMGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property String 1.
        /// </summary>
        internal static string FRMLBL_PSD_PROPERTYSTRING1 {
            get {
                return ResourceManager.GetString("FRMLBL_PSD_PROPERTYSTRING1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property String 2.
        /// </summary>
        internal static string FRMLBL_PSD_PROPERTYSTRING2 {
            get {
                return ResourceManager.GetString("FRMLBL_PSD_PROPERTYSTRING2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property String 3.
        /// </summary>
        internal static string FRMLBL_PSD_PROPERTYSTRING3 {
            get {
                return ResourceManager.GetString("FRMLBL_PSD_PROPERTYSTRING3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property String 4.
        /// </summary>
        internal static string FRMLBL_PSD_PROPERTYSTRING4 {
            get {
                return ResourceManager.GetString("FRMLBL_PSD_PROPERTYSTRING4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property String 5.
        /// </summary>
        internal static string FRMLBL_PSD_PROPERTYSTRING5 {
            get {
                return ResourceManager.GetString("FRMLBL_PSD_PROPERTYSTRING5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property String 6.
        /// </summary>
        internal static string FRMLBL_PSD_PROPERTYSTRING6 {
            get {
                return ResourceManager.GetString("FRMLBL_PSD_PROPERTYSTRING6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property String 7.
        /// </summary>
        internal static string FRMLBL_PSD_PROPERTYSTRING7 {
            get {
                return ResourceManager.GetString("FRMLBL_PSD_PROPERTYSTRING7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property String 8.
        /// </summary>
        internal static string FRMLBL_PSD_PROPERTYSTRING8 {
            get {
                return ResourceManager.GetString("FRMLBL_PSD_PROPERTYSTRING8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property String Label.
        /// </summary>
        internal static string FRMLBL_PSN_PROPERTYSTRINGLABEL {
            get {
                return ResourceManager.GetString("FRMLBL_PSN_PROPERTYSTRINGLABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property String Name.
        /// </summary>
        internal static string FRMLBL_PSN_PROPERTYSTRINGNAME {
            get {
                return ResourceManager.GetString("FRMLBL_PSN_PROPERTYSTRINGNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property String Order.
        /// </summary>
        internal static string FRMLBL_PSN_PROPERTYSTRINGORDER {
            get {
                return ResourceManager.GetString("FRMLBL_PSN_PROPERTYSTRINGORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Your Own File GUID.
        /// </summary>
        internal static string FRMLBL_TFG_CMDNAMEYOUROWNFILEGUID {
            get {
                return ResourceManager.GetString("FRMLBL_TFG_CMDNAMEYOUROWNFILEGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File GUID.
        /// </summary>
        internal static string FRMLBL_TFG_CMDNEWFILEGUID {
            get {
                return ResourceManager.GetString("FRMLBL_TFG_CMDNEWFILEGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File GUID.
        /// </summary>
        internal static string FRMLBL_TFG_TXTFILEGUID {
            get {
                return ResourceManager.GetString("FRMLBL_TFG_TXTFILEGUID", resourceCulture);
            }
        }
    }
}
