//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string CMD_ARG_INPUT {
            get {
                return ResourceManager.GetString("CMD_ARG_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern.
        /// </summary>
        internal static string CMD_ARG_PATTERN {
            get {
                return ResourceManager.GetString("CMD_ARG_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReplaceWith.
        /// </summary>
        internal static string CMD_ARG_REPLACEWITH {
            get {
                return ResourceManager.GetString("CMD_ARG_REPLACEWITH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input string is expected to be the text of a label, followed by a standard Format Item..
        /// </summary>
        internal static string ERRMSG_MISSING_FORMAT_ITEM {
            get {
                return ResourceManager.GetString("ERRMSG_MISSING_FORMAT_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please press Return to fully stop the program..
        /// </summary>
        internal static string MSG_AWAIT_CARBON_UNIT {
            get {
                return ResourceManager.GetString("MSG_AWAIT_CARBON_UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no further exceptions to report.{0}.
        /// </summary>
        internal static string MSG_EXCEPTION_REPORT_EPOLOGUE_END {
            get {
                return ResourceManager.GetString("MSG_EXCEPTION_REPORT_EPOLOGUE_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an {0} Inner Exception, {1}.{2}.
        /// </summary>
        internal static string MSG_EXCEPTION_REPORT_EPOLOGUE_MORE {
            get {
                return ResourceManager.GetString("MSG_EXCEPTION_REPORT_EPOLOGUE_MORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          Method (TargetSite) = {0}.
        /// </summary>
        internal static string MSG_EXCEPTION_REPORT_METHOD {
            get {
                return ResourceManager.GetString("MSG_EXCEPTION_REPORT_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2}An {0} exception occurred.{2}Details: Message             = {1}.
        /// </summary>
        internal static string MSG_EXCEPTION_REPORT_PROLOGUE {
            get {
                return ResourceManager.GetString("MSG_EXCEPTION_REPORT_PROLOGUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          Source              = {0}.
        /// </summary>
        internal static string MSG_EXCEPTION_REPORT_SOURCE {
            get {
                return ResourceManager.GetString("MSG_EXCEPTION_REPORT_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          StackTrace          = {0}.
        /// </summary>
        internal static string MSG_EXCEPTION_REPORT_STACKTRACE {
            get {
                return ResourceManager.GetString("MSG_EXCEPTION_REPORT_STACKTRACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputs:  Input       = {0}.
        /// </summary>
        internal static string MSG_INPUTS_INPUT {
            get {
                return ResourceManager.GetString("MSG_INPUTS_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          Pattern     = {0}.
        /// </summary>
        internal static string MSG_INPUTS_PATTERN {
            get {
                return ResourceManager.GetString("MSG_INPUTS_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          ReplaceWith = {0}.
        /// </summary>
        internal static string MSG_INPUTS_REPLACE_WITH {
            get {
                return ResourceManager.GetString("MSG_INPUTS_REPLACE_WITH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INPUT ERROR: Named command line argument {0} is missing..
        /// </summary>
        internal static string MSG_MISSING_ARG {
            get {
                return ResourceManager.GetString("MSG_MISSING_ARG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}{0} required command line arguments are missing. Execution cannot continue.{1}.
        /// </summary>
        internal static string MSG_MISSING_ARGS_COUNT {
            get {
                return ResourceManager.GetString("MSG_MISSING_ARGS_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outputs: IsMatch     = {0}.
        /// </summary>
        internal static string MSG_OUTPUTS_ISMATCH {
            get {
                return ResourceManager.GetString("MSG_OUTPUTS_ISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          Match {0}     = {1}.
        /// </summary>
        internal static string MSG_OUTPUTS_MATCHES {
            get {
                return ResourceManager.GetString("MSG_OUTPUTS_MATCHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          Replacement = {0}.
        /// </summary>
        internal static string MSG_OUTPUTS_REPLACEMENT {
            get {
                return ResourceManager.GetString("MSG_OUTPUTS_REPLACEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}         Execute     = {0}{1}.
        /// </summary>
        internal static string MSG_PROGRESS_EXECUTE {
            get {
                return ResourceManager.GetString("MSG_PROGRESS_EXECUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, version {1}.{2}{5}{3} ({4} UTC){5}.
        /// </summary>
        internal static string MSG_START {
            get {
                return ResourceManager.GetString("MSG_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {4}{0} Done, {1} ({2} UTC){4}Running time = {3}.
        /// </summary>
        internal static string MSG_STOP {
            get {
                return ResourceManager.GetString("MSG_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test host sees the following..
        /// </summary>
        internal static string MSG_TEST_HOST_REPORT {
            get {
                return ResourceManager.GetString("MSG_TEST_HOST_REPORT", resourceCulture);
            }
        }
    }
}
