//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.2053.0.
// 
namespace SharedUtl4_TestStand_Settings {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/2004/01/settings")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/VisualStudio/2004/01/settings", IsNullable=false)]
    public partial class SettingsFile {
        
        private string profilesField;
        
        private SettingsFileSettingsSetting[][] settingsField;
        
        private string currentProfileField;
        
        private string generatedClassNamespaceField;
        
        private string generatedClassNameField;
        
        /// <remarks/>
        public string Profiles {
            get {
                return this.profilesField;
            }
            set {
                this.profilesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Setting", typeof(SettingsFileSettingsSetting), IsNullable=false)]
        public SettingsFileSettingsSetting[][] Settings {
            get {
                return this.settingsField;
            }
            set {
                this.settingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CurrentProfile {
            get {
                return this.currentProfileField;
            }
            set {
                this.currentProfileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string GeneratedClassNamespace {
            get {
                return this.generatedClassNamespaceField;
            }
            set {
                this.generatedClassNamespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string GeneratedClassName {
            get {
                return this.generatedClassNameField;
            }
            set {
                this.generatedClassNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/2004/01/settings")]
    public partial class SettingsFileSettingsSetting {
        
        private SettingsFileSettingsSettingValue[] valueField;
        
        private string nameField;
        
        private string typeField;
        
        private string scopeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value", IsNullable=true)]
        public SettingsFileSettingsSettingValue[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Scope {
            get {
                return this.scopeField;
            }
            set {
                this.scopeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/2004/01/settings")]
    public partial class SettingsFileSettingsSettingValue {
        
        private string profileField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Profile {
            get {
                return this.profileField;
            }
            set {
                this.profileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/VisualStudio/2004/01/settings")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/VisualStudio/2004/01/settings", IsNullable=false)]
    public partial class NewDataSet {
        
        private SettingsFile[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SettingsFile")]
        public SettingsFile[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
}
